### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by pervoj** [Prince781/valdo#2]
Compilation fails when using:
```
meson _build
cd _build
sudo ninja install
```

Error messages:
![screenshot – errors](https://user-images.githubusercontent.com/71781857/122462598-15667b00-cfb5-11eb-89df-26983282b8c3.png)

**Comment by Prince781** [comment]
Good catch. You need Vala 0.52 or higher (I think) since the source uses the `with` keyword.

**Comment by pervoj** [comment]
And where can I get version 0.52 for Fedora?

**Comment by Prince781** [comment]
@pervoj do a `git pull` now. Valdo should be able to build with your version of Vala (0.48)

**Comment by pervoj** [comment]
Thank you!

But I compilation failed again. I solved it: in `src/value.vala` replace 32nd line with:
```vala
var substring = value_pattern[end_pos:value_pattern.length];
```

**Comment by Prince781** [comment]
Okay, I think this is resolved now.
